### ISSUE TITLE
Unable to open setting on php 8.0

### ISSUE THREAD

**Issue by alexdryden** [RBoelter/citations#12]
**Describe the bug**
When activating the plugin for a journal for the first time, the administrator is getting and invalid JSON error when they try to open the plugin settings and a php error is generated:
```
[Fri Mar 17 14:12:49.140640 2023] [php:error] [pid 39507] [client xx.xx.xx.xx:xxxx] PHP Fatal error:  Uncaught AssertionError: assert(isset($params['id'])) in /var/www/ojs/lib/pkp/classes/form/FormBuilderVocabulary.inc.php:116Stack trace:
#0 /var/www/ojs/lib/pkp/classes/form/FormBuilderVocabulary.inc.php(116): assert(false, 'assert(isset($p...')
#1 /var/www/ojs/cache/t_compile/cd5329b7a22e82788ebdd3335651669dda8c9df1^6e5b8fb83fe9660aa95a27d924b2f57a8d7bb78d_0.plugins-3-plugins-generic-citations-generic-citations.settings.tpl.php(55): FormBuilderVocabulary->smartyFBVFormArea(Array, NULL, Object(Smarty_Internal_Template), true)
#2 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6414b7decbbb39_10296392(Object(Smarty_Internal_Template))
#3 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#4 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#5 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#6 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, 'cd5329b7a22e827...', NULL, 0)
#7 /var/www/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1072): Smarty_Internal_TemplateBase->fetch('plugins-3-plugi...', NULL, 'cd5329b7a22e827...', NULL)
#8 /var/www/ojs/lib/pkp/classes/form/Form.inc.php(197): PKPTemplateManager->fetch('plugins-3-plugi...')
#9 /var/www/ojs/plugins/generic/citations/CitationsSettingsForm.inc.php(47): Form->fetch(Object(Request), NULL, false)
#10 /var/www/ojs/plugins/generic/citations/CitationsPlugin.inc.php(132): CitationsSettingsForm->fetch(Object(Request))
#11 /var/www/ojs/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(236): CitationsPlugin->manage(Array, Object(Request))
#12 /var/www/ojs/lib/pkp/classes/core/PKPRouter.inc.php(395): PluginGridHandler->manage(Array, Object(Request))
#13 /var/www/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#14 /var/www/ojs/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request))
#15 /var/www/ojs/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#16 /var/www/ojs/index.php(68): PKPApplication->execute()
#17 {main}  thrown in /var/www/ojs/lib/pkp/classes/form/FormBuilderVocabulary.inc.php on line 116, referer: https://iopn.library.illinois.edu/journals/jams/management/settings/website
```

**To Reproduce**
1. Activate the plugin from the gallery
2. Go to installed plugins and click "Settings" under Scopus/Crossref Plugin 
3. See error message

**What application are you using?**
 OJS version 3.3.0-13 php 8.0.x

**Additional information**
Similar to https://github.com/pkp/pkp-lib/issues/8757

**Comment by alexdryden** [comment]
Using https://github.com/pkp/citationStyleLanguage/pull/106/files#diff-b8707cd533069c8870eaa04e448d847ac5c961127d9f3d97724165680ad671d1 as a model, adding an id to the templates/settings.tpl fixes the issue.
